#
###################################
# Site wide configuration
####################################
#
title: Krishna Kannan
email: krishna.kay@gmail.com
description: Welcome - Krishna Kannan
url: http://krishnakannan.com
keywords: ["Proramming", "Java", "Android", "Data structures", "Algorithms", "Distributed Systems", "Distributed Architectures", "Problem Solving", "Raspberry Pi", "Cluster", "Cluster Computing", "RaspberryPi", "RaspberryPi Cluster", "RPi"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Singapore
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title


# Plugins
plugins:
  - jekyll-paginate

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate

paginate: 4
paginate_path: "/page:num/"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Krishna Kannan
  avatar: 
  job: "Software Engineer"
  bio: "Passionate Coder. Opensource Contributor. Working as Research Engineer in Singapore"
  email: krishna.kay@gmail.com
  disqus-shortname: #Krish'sBlog
  twitter:  #username
  facebook: krish.na.18062 #username
  google:
    plus: #username
    analytics: UA-78966348-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: krishnakannan #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: kannankrishna #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
